/**
 * Comprehensive icon mapping for standard amenities
 * Maps amenity names to lucide-react icon components
 * 
 * The icon field in standard_amenities table should store the icon name (e.g., "Wifi", "Car")
 * This file provides the mapping from icon name to actual icon component
 */

import {
  // Connectivity & Technology
  Wifi,
  Radio,
  Tv,
  Smartphone,
  Zap,
  // Room Comfort
  Wind,
  Snowflake,
  Sun,
  Bed,
  Sofa,
  DoorOpen,
  // Bathroom
  Droplets,
  ShowerHead,
  // Food & Beverage
  UtensilsCrossed,
  Coffee,
  ChefHat,
  // Recreation
  Waves,
  Dumbbell,
  Flower2,
  // Services
  ConciergeBell,
  Car,
  Plane,
  Shirt,
  Clock,
  // Family & Pets
  Baby,
  PawPrint,
  // Business
  Briefcase,
  // Safety
  Shield,
  Lock,
  // Accessibility
  Accessibility,
  // Nature & Location
  Mountain,
  TreePine,
  MapPin,
  // Entertainment
  Gamepad2,
  BookOpen,
  // Other
  Sparkles,
  Flame,
  Leaf,
  Heart,
  Star,
  Gift,
  Camera,
  Music,
  Bike,
  CarFront,
  Building,
  Home,
  Hotel,
  Users,
  UserCheck,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  HelpCircle,
  Search,
  Filter,
  Settings,
  Menu,
  MoreVertical,
  Plus,
  Minus,
  Edit,
  Trash2,
  Save,
  X,
  Check,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  ArrowDown,
  ArrowUp,
  // Additional icons for amenities
  Umbrella,
} from "lucide-react";

// Comprehensive icon mapping
// Maps amenity names (normalized) to icon components
export const amenityIconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  // Connectivity & Technology
  "Wifi": Wifi,
  "Free Wi-Fi": Wifi,
  "Wi-Fi": Wifi,
  "High-Speed Internet": Wifi,
  "Internet Access": Wifi,
  "Wireless Internet": Wifi,
  "Fiber Optic Internet": Wifi,
  "TV": Tv,
  "Flat-Screen TV": Tv,
  "Smart TV": Tv,
  "Streaming Services": Tv,
  "Cable TV": Tv,
  "Satellite TV": Tv,
  "DVD Player": Tv,
  "Sound System": Music,
  "Radio": Radio,
  "USB Charging Ports": Zap,
  "Power Outlets": Zap,
  "Universal Power Adapters": Zap,
  "Wireless Charging": Zap,
  "Smartphone": Smartphone,

  // Room Comfort & Essentials
  "Air Conditioning": Snowflake,
  "Heating": Sun,
  "Ceiling Fan": Wind,
  "Fan": Wind,
  "Climate Control": Wind,
  "Bed Linens": Bed,
  "Pillows": Bed,
  "Extra Pillows": Bed,
  "Hypoallergenic Bedding": Bed,
  "Pillow Menu": Bed,
  "Blackout Curtains": Bed,
  "Window Treatments": Bed,
  "Wardrobe": DoorOpen,
  "Closet": DoorOpen,
  "Dresser": Sofa,
  "Luggage Rack": Sofa,
  "Hangers": Shirt,
  "Drawers": Sofa,
  "Safe": Lock,
  "In-Room Safe": Lock,
  "Ironing Board": Shirt,
  "Iron": Shirt,
  "Desk": Briefcase,
  "Work Desk": Briefcase,
  "Chair": Sofa,
  "Sofa": Sofa,
  "Seating Area": Sofa,
  "Balcony": Home,
  "Terrace": Home,
  "Patio": Home,
  "Private Entrance": DoorOpen,
  "Private Bathroom": Droplets,
  "Ensuite Bathroom": Droplets,
  "Shared Bathroom": Droplets,
  "Interconnecting Rooms": DoorOpen,
  "Adjoining Rooms": DoorOpen,
  "Soundproofing": Shield,
  "City View": Building,
  "Garden View": Flower2,
  "Sea View": Waves,
  "Mountain View": Mountain,
  "Pool View": Waves,
  "River View": Waves,
  "Lake View": Waves,

  // Bathroom & Personal Care
  "Towels": Droplets,
  "Bath Towels": Droplets,
  "Hand Towels": Droplets,
  "Face Towels": Droplets,
  "Bath Mat": Droplets,
  "Toilet Paper": Droplets,
  "Tissues": Droplets,
  "Soap": Droplets,
  "Shampoo": Droplets,
  "Conditioner": Droplets,
  "Body Wash": Droplets,
  "Body Lotion": Droplets,
  "Hand Soap": Droplets,
  "Toiletries": Droplets,
  "Hairdryer": ShowerHead,
  "Hair Dryer": ShowerHead,
  "Shower Cap": Droplets,
  "Bathrobe": Shirt,
  "Slippers": Shirt,
  "Mirror": Camera,
  "Vanity Mirror": Camera,
  "Makeup Mirror": Camera,
  "Shaving Kit": Droplets,
  "Comb": Droplets,
  "Cotton Swabs": Droplets,
  "Cotton Pads": Droplets,
  "Bathtub": ShowerHead,
  "Shower": ShowerHead,
  "Hot Water": Droplets,
  "Bidet": Droplets,
  "Towel Rack": Droplets,
  "Toiletries Basket": Droplets,

  // Food & Beverage
  "Mini Bar": UtensilsCrossed,
  "Mini Fridge": UtensilsCrossed,
  "Refrigerator": UtensilsCrossed,
  "Microwave": UtensilsCrossed,
  "Coffee Maker": Coffee,
  "Tea/Coffee Maker": Coffee,
  "Electric Kettle": Coffee,
  "Water Kettle": Coffee,
  "Coffee/Tea Supplies": Coffee,
  "Complimentary Water": Droplets,
  "Complimentary Tea/Coffee": Coffee,
  "Snacks": UtensilsCrossed,
  "Complimentary Breakfast": UtensilsCrossed,
  "Continental Breakfast": UtensilsCrossed,
  "Full Breakfast": UtensilsCrossed,
  "Breakfast Included": UtensilsCrossed,
  "Restaurant": UtensilsCrossed,
  "On-Site Restaurant": UtensilsCrossed,
  "Bar": UtensilsCrossed,
  "Room Service": ConciergeBell,
  "Dining Area": UtensilsCrossed,
  "Outdoor Dining": UtensilsCrossed,
  "BBQ Facilities": Flame,
  "Barbecue": Flame,
  "Kitchen": ChefHat,
  "Kitchenette": ChefHat,
  "Fully Equipped Kitchen": ChefHat,
  "Cooking Facilities": ChefHat,
  "Dining Table": UtensilsCrossed,

  // Property Facilities & Services
  "Swimming Pool": Waves,
  "Outdoor Pool": Waves,
  "Indoor Pool": Waves,
  "Pool": Waves,
  "Hot Tub": Waves,
  "Jacuzzi": Waves,
  "Spa": Heart,
  "Wellness Center": Heart,
  "Fitness Center": Dumbbell,
  "Gym": Dumbbell,
  "Exercise Room": Dumbbell,
  "Yoga Area": Flower2,
  "Garden": Flower2,
  "Outdoor Space": Flower2,
  "Rooftop Terrace": Home,
  "Playground": Baby,
  "Games Room": Gamepad2,
  "Library": BookOpen,
  "Lounge": Sofa,
  "Common Area": Sofa,
  "Shared Lounge": Sofa,
  "Business Center": Briefcase,
  "Meeting Room": Briefcase,
  "Conference Room": Briefcase,
  "Business Services": Briefcase,
  "Fax/Photocopying": Briefcase,
  "Printing Services": Briefcase,
  "24-Hour Front Desk": Clock,
  "Reception": ConciergeBell,
  "Concierge Service": ConciergeBell,
  "Housekeeping": Shirt,
  "Daily Housekeeping": Shirt,
  "Laundry Service": Shirt,
  "Dry Cleaning": Shirt,
  "Luggage Storage": Briefcase,
  "Baggage Storage": Briefcase,
  "Airport Shuttle": Plane,
  "Shuttle Service": Car,
  "Transportation Services": Car,
  "Car Rental": Car,
  "Tour Desk": MapPin,
  "Ticket Service": Gift,
  "Free Parking": Car,
  "Parking": Car,
  "On-Site Parking": Car,
  "Valet Parking": Car,
  "Street Parking": Car,
  "Secure Parking": Car,
  "Garage": Car,
  "Electric Vehicle Charging": Zap,
  "Bicycle Rental": Bike,

  // Safety & Security
  "Smoke Detector": Shield,
  "Fire Extinguisher": Shield,
  "First Aid Kit": Shield,
  "Security System": Shield,
  "CCTV": Camera,
  "Security Cameras": Camera,
  "Lockers": Lock,
  "Key Card Access": Lock,
  "Electronic Locks": Lock,
  "Deadbolt Lock": Lock,
  "Emergency Lighting": AlertCircle,
  "Emergency Exit": DoorOpen,
  "Fire Safety Equipment": Shield,
  "Backup Power": Zap,

  // Accessibility Features
  "Wheelchair Accessible": Accessibility,
  "Accessible Parking": Accessibility,
  "Accessible Entrance": Accessibility,
  "Accessible Bathroom": Accessibility,
  "Accessible Room": Accessibility,
  "Elevator": Building,
  "Lift": Building,
  "Ramp Access": Accessibility,
  "Wide Doorways": DoorOpen,
  "Lowered Light Switches": Settings,
  "Grab Bars": Shield,
  "Roll-in Shower": ShowerHead,
  "Hearing Accessible": Users,
  "Visual Accessible": Users,
  "Braille Signage": BookOpen,

  // Family & Children
  "Family Rooms": Users,
  "Extra Beds": Bed,
  "Crib": Baby,
  "Baby Crib": Baby,
  "High Chair": Baby,
  "Baby High Chair": Baby,
  "Children's Playground": Baby,
  "Kids' Club": Baby,
  "Children's Activities": Baby,
  "Babysitting Service": Baby,
  "Childcare Services": Baby,
  "Kids' Menu": UtensilsCrossed,
  "Children's Pool": Waves,

  // Pet-Friendly Features
  "Pet Friendly": PawPrint,
  "Pets Allowed": PawPrint,
  "Pet Bowls": PawPrint,
  "Pet Bed": PawPrint,
  "Pet Sitting": PawPrint,
  "Dog Walking Service": PawPrint,
  "Pet Area": PawPrint,

  // Special Features & Luxury
  "Premium Toiletries": Gift,
  "Designer Toiletries": Gift,
  "Bath Salts": Droplets,
  "Scented Candles": Flame,
  "Welcome Gift": Gift,
  "Welcome Drink": Coffee,
  "Turndown Service": Bed,
  "Butler Service": ConciergeBell,
  "Personal Concierge": ConciergeBell,
  "Premium Bedding": Bed,
  "Luxury Linens": Bed,
  "Spa Services": Heart,
  "Massage Services": Heart,
  "Sauna": Waves,
  "Steam Room": Waves,
  "Hot Stone Massage": Heart,
  "Aromatherapy": Flower2,
  "Yoga Classes": Flower2,
  "Meditation Area": Flower2,
  "Air Purifier": Wind,
  "Humidifier": Droplets,
  "Game Room": Gamepad2,
  "Billiards": Gamepad2,
  "Table Tennis": Gamepad2,
  "Tennis Court": Gamepad2,
  "Golf Course": TreePine,
  "Water Sports": Waves,
  "Diving": Waves,
  "Snorkeling": Waves,
  "Fishing": Waves,
  "Hiking": Mountain,
  "Bicycle Tours": Bike,

  // Location & Surroundings
  "Beach Access": Waves,
  "Beachfront": Waves,
  "Waterfront": Waves,
  "City Center": Building,
  "Near Airport": Plane,
  "Near Train Station": Car,
  "Near Metro": Car,
  "Near Shopping": Building,
  "Near Restaurants": UtensilsCrossed,
  "Near Attractions": MapPin,
  "Quiet Location": Leaf,
  "Scenic Location": Mountain,

  // Policies & Services
  "Early Check-in": Clock,
  "Late Check-out": Clock,
  "Flexible Check-in/Check-out": Clock,
  "Express Check-in/Check-out": Clock,
  "Contactless Check-in": Smartphone,
  "Mobile Check-in": Smartphone,
  "Keyless Entry": Lock,
  "Self Check-in": DoorOpen,
  "Lockbox": Lock,
  "Long Stay Discount": Gift,
  "Weekly/Monthly Rates": Gift,
  "Extended Stay": Clock,
  "Non-Smoking Rooms": XCircle,
  "Smoking Area": Flame,
  "Smoking Allowed": Flame,
  "No Smoking": XCircle,

  // Eco-Friendly & Sustainability
  "Eco-Friendly": Leaf,
  "Green Building": Leaf,
  "Solar Power": Sun,
  "Water Conservation": Droplets,
  "Recycling": Leaf,
  "Organic Products": Leaf,
  "Local Products": MapPin,
  "Sustainable Practices": Leaf,
  "Carbon Neutral": Leaf,

  // Language & Communication
  "Multilingual Staff": Users,
  "English Speaking Staff": Users,
  "Translation Services": Users,
  "Local Language Support": Users,
};

/**
 * Get icon component for an amenity
 * @param amenity - Amenity object with name and optional icon field
 * @returns Icon component or default Sparkles icon
 */
export function getAmenityIcon(amenity: { name: string; icon?: string | null }): React.ComponentType<{ className?: string }> {
  // First try to use the icon field from database (should be a lucide-react icon name)
  if (amenity.icon) {
    // If icon is stored as a component name (e.g., "Wifi", "Car"), try to find it in the map
    const iconFromDb = amenityIconMap[amenity.icon];
    if (iconFromDb) {
      return iconFromDb;
    }
  }

  // Fallback: try to match by amenity name
  const normalizedName = amenity.name.trim();
  const iconByName = amenityIconMap[normalizedName];
  if (iconByName) {
    return iconByName;
  }

  // Default fallback
  return Sparkles;
}
